[project]
name = "coriolis_pdk_sky130_fd_pr"
version = "0.1.0"
description = "Sky130 FD PR PDK for Coriolis EDA"
authors = [ { name = "Coriolis EDA Contributers" } ]
requires-python = ">= 3.9"
dependencies = [
  "coriolis_eda",
]

[build-system]
requires = [
  "meson",
  "meson-python",
  "ninja",
  "setuptools",
  "cibuildwheel",
  "build",
  "pdm-backend"
]
build-backend = "mesonpy"

[tool.cibuildwheel]
build = "cp310-*"
skip = ["cp36-*", "cp37-*", "cp38-*", "cp39-*", "pp*"]
