[project]
name = "coriolis_cells_lsxram"
version = "0.1.0"
description = "LSXRAM IP for Coriolis EDA"
authors = [ { name = "Coriolis EDA Contributers" } ]
requires-python = ">= 3.9"
dependencies = [
  "coriolis-eda",
  "coriolis_cells_lsxlib"
]

[tool.setuptools.packages.find]
where = ["."]
include = [
  "coriolis.IP.lsxram",
  "coriolis.IP.lsxram.*"
]

[tool.setuptools.package-data]
lsxram = [
  "*.c",
  "*.ap",
  "*.vbe"
]

[build-system]
requires = [
    "setuptools",
    "cibuildwheel",
    "build",
    "pdm-backend"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp310-*"
skip = ["cp36-*", "cp37-*", "cp38-*", "cp39-*", "pp*"]
