volumes:
  coriolis-workspace:

services:
  coriolis-eda:
    build:
      context: .
      dockerfile: ./coriolis-eda.dockerfile
      args:
        - CORIOLIS_URL=${CORIOLIS_URL}
        - CORIOLIS_BRANCH=${CORIOLIS_BRANCH}
        - ALLIANCE_URL=${ALLIANCE_URL}
        - ALLIANCE_BRANCH=${ALLIANCE_BRANCH}
        - ALLIANCE_CT_URL=${ALLIANCE_CT_URL}
        - ALLIANCE_CT_BRANCH=${ALLIANCE_CT_BRANCH}
    env_file: .env
    image: coriolis-eda:ubuntu24.04
    container_name: coriolis-eda
    hostname: coriolis-eda
    restart: unless-stopped
    volumes:
      - coriolis-workspace:/home/developer/coriolis-2.x
    command: ["sleep", "infinity"]
    networks:
      - host

networks:
  host:
    driver: bridge
