volumes:
  coriolis-workspace:

services:
  coriolis-eda:
    build:
      context: .
      dockerfile: ./coriolis-eda.dockerfile
    image: coriolis-eda:ubuntu24.04
    container_name: coriolis-eda
    hostname: coriolis-eda
    restart: unless-stopped
    volumes:
      - coriolis-workspace:/home/developer/coriolis-2.x
    environment:
      - CORIOLIS_URL=${CORIOLIS_URL}
      - CORIOLIS_BRANCH=${CORIOLIS_BRANCH}
      - ALLIANCE_URL=${ALLIANCE_URL}
      - ALLIANCE_BRANCH=${ALLIANCE_BRANCH}
      - ALLIANCE_CT_URL=${ALLIANCE_CT_URL}
      - ALLIANCE_CT_BRANCH=${ALLIANCE_CT_BRANCH}
      - VENV_PATH=/home/developer/coriolis-2.x/src/coriolis/.venv
      - BUILD_TYPE=release
      - SRC_DIR=/home/developer/coriolis-2.x/src/coriolis
      - OUT_DIR=/home/developer/coriolis-2.x/src/coriolis/docker/ubuntu24.04
    command: bash -c "/home/developer/setup-coriolis-workspace.sh && sleep infinity"
    networks:
      - host

networks:
  host:
    driver: bridge
