[project]
name = "coriolis_cells_sky130"
version = "0.1.0"
description = "Sky130 cells library for Coriolis EDA"
authors = [ { name = "Coriolis EDA Contributers" } ]
requires-python = ">= 3.9"

[tool.setuptools.packages.find]
where = ["."]
include = ["coriolis"]

[tool.setuptools.package-data]
sky130 = [
  "*.c",
  "*.ap",
  "*.vbe"
]

[build-system]
requires = [
    "setuptools",
    "cibuildwheel",
    "build",
    "pdm-backend"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp310-*"
skip = ["cp36-*", "cp37-*", "cp38-*", "cp39-*", "pp*"]
